#!/usr/bin/perl
use warnings;
use diagnostics;
use strict;
use 5.010;

{
my $bingo = int(1 +rand(100));
chomp($ARGV[0]);
if (defined $ARGV[0] && $ARGV[0] eq '-w') {
	say "The secret number is $bingo";
}
	while(1) {
		say "Enter your guess";
		chomp(my $guess = <STDIN>);
		if ($guess =~ /\A(quit|exit|\s+|\D+)\z/i){
			last;	
		}
		elsif ($guess == $bingo) {
			say "Bingo!";
			last;
		}
		elsif ($guess > $bingo) {
			say "Too high";
			next;
		}
		else {
			say "Too low";
			next;
		} 
	}
}
