#!/usr/bin/perl -w
use strict;
use 5.010;

{
	say "Please enter the first number";
	chomp(my $first_num = <STDIN>);
	say "Please enter the secondt number";
	chomp(my $second_num = <STDIN>);
	my $product = $first_num * $second_num;
	say "The product of $first_num and $second_num is $product";
}
