#!/usr/bin/perl -w
use strict;
use 5.010;

{
	say "Please enter one string";
	chomp(my $input = <STDIN>);
	say "Please enter times you want to repeat";
	chomp(my $times = <STDIN>);
	print "$input\n" x $times;
}
