#!/usr/bin/perl -w
use strict;
use 5.010;

{
my $pie = 3.141592654;
my $perimeter;
print "Please enter the raidus: ";
chomp(my $radius = <STDIN>);
if ($radius < 0) {
	$perimeter = 0;
} elsif ($radius >= 0) {
	$perimeter = 2 * $pie * $radius;
} else {
	die "Please enter a number larger than 0.";
}
say "The perimeter of a circle with radius $radius is $perimeter.";
}
