#!/usr/bin/perl
use warnings;
use diagnostics;
use strict;
use 5.010;

while(<>) {
	chomp;
	if (/(?<word>\b\w*a\b)(?<after>.{0,5})/s) {
		say "'word' contains '$+{word}', 'after' contains '$+{after}'";
	} else {
		say "No match: |$_|";
	}
}
