#!/usr/bin/perl -w
use strict;
use diagnostics;
use 5.010;

my @fred = above_average(1..10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100, 1..10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";

sub above_average {
	my $avg = average(@_);
	my @above;
	for my $current (@_) {
		if ($current > $avg) {
			push (@above,$current);
		}
	}
	return "@above";
}

sub average {
	my $sum = 0;
	for my $number (@_) {
		$sum += $number; 
	}
	$sum/@_;
}
