#!/usr/bin/perl
## Copyright (C) 2015 by Daniel XU
## Copyright (C) 2015 by Daniel XU
use warnings;
use diagnostics;
use strict;
use 5.010;

$^I = ".bak";
while(<>) {
	s/(perl\Z\n)/$1## Copyright (C) 2015 by Daniel XU\n/gi;
	print;
}
